cloudinary_sdk.settings:
  type: config_object
  label: 'Cloudinary SDK Settings'
  mapping:
    cloudinary_sdk_cloud_name:
      label: 'Cloud Name'
      type: string
    cloudinary_sdk_upload_prefix:
      label: 'Upload prefix'
      type: string
    cloudinary_sdk_cname:
      label: 'CNAME'
      type: string
    cloudinary_sdk_api_key:
      label: 'API Key'
      type: string
    cloudinary_sdk_api_secret:
      label: 'API Secret'
      type: string
